#!/bin/bash

user=$(ls /home/)

if (ls /tmp | grep backup)
then
:
else
mkdir /tmp/backup/
fi

cp /home/$user/.bashrc /tmp/backup/$user-bashrc
cp /root/.bashrc /tmp/backup/root-bashrc
cp /usr/share/themes/bash-theme /home/$user/.bashrc
mv /usr/share/themes/bash-theme /root/.bashrc
chmod 777 /home/$user/.bashrc

echo -e "\033[31m 如果你发现bash不能正常使用，去/tmp/backup/目录恢复bashrc文件 \033[0m"

if (ls  -a /home/$user/ | grep .conky > /dev/null 2>&1)
then
:
else
mkdir /home/$user/.conky/
fi

mv /usr/share/themes/conky-theme/ /home/$user/.conky/&&chmod 777 /home/$user/.conky -R
